### ISSUE TITLE
Update snapcast to v0.21.0

### ISSUE THREAD

**Issue by l3d00m** [IVData/dockerfiles#12]
Hi,

first of all thanks for the images, it's really helpful for me! Could you update the snapserver/client images to the new version, see https://github.com/badaix/snapcast/releases

Thanks a lot!

**Comment by hamishfagg** [comment]
I've updated both the client and server. Can you please test them out and see if they work. Especially the web page on the server.

**Comment by l3d00m** [comment]
I'll try to check the server tomorrow, I don't have the client dockerized unfortunately. Thanks!

**Comment by l3d00m** [comment]
Sorry for the delay, I got the snapserver to work now. 

For some reason the mDNS discovery of snapserver did not work with this version of the docker image (pretty sure it worked on the version before) and I got it to work by adding the following to my docker-compose `volumes` of snapserver. Not sure how safe this is or if it's good practice, I've never really worked with mdns/dbus before.
```yaml
  snapserver:
    container_name: snapserver
    restart: unless-stopped
    image: ivdata/snapserver:latest
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    volumes:
      - /var/run/dbus:/var/run/dbus # THIS ONE seems to be neccessary for avahi/mDNS??
```

Also the web UI on port 1780 doesn't seem to work, according to the [docs](https://github.com/badaix/snapcast/tree/v0.21.0#control) there should be a UI reachable under that port, but it only says `The resource '/' was not found.` for me
