### ISSUE TITLE
install DLNA Renderer ?

### ISSUE THREAD

**Issue by Kollisionskurs** [IVData/dockerfiles#16]
Hi,
first of all thanks for the images !! I'm a docker Newbie and I need a tip. 
I want to install a dlna renderer - so i can stream music from my smartphone to mopidy ... how can I do that ? 

my Stack:

version: "2.1"
services:
  mopidy:
    image: ivdata/mopidy:latest
    container_name: mopidy
    hostname: mopidy
    volumes:
    - /srv/dev-disk-by-label-cfusb/docker/mopidy/snapserver/fifo:/tmp/snapcast
    - /srv/dev-disk-by-label-cfusb/docker/mopidy/music:/media/music
    - /srv/dev-disk-by-label-cfusb/docker/mopidy:/mopidy
    environment: 
    # - APT_PACKAGES='upmpdcli'
    - PIP_PACKAGES='Mopidy-dLeyna'
    ports:
    - "6680:6680"
    - "6600:6600"
  snapserver:
    image: ivdata/snapserver:latest
    container_name: snapserver
    hostname: snapserver
    volumes:
    - /srv/dev-disk-by-label-cfusb/docker/mopidy/snapserver/fifo:/tmp/snapcast/
    ports:
    - "1704:1704"
    - "1705:1705"
    - "1780:1780"
    restart: unless-stopped

thanks

**Comment by spiro-c** [comment]
You can install like this but Mopidy-dLeyna or other extension but, Mopidy-dLeyna will not work it missing some other packages in the docker image 
`libdbus-glib-1-dev
dleyna-server
dbus-python`
and plus u need to pass host network to docker
```
mopidy:
    image: "ivdata/mopidy"
    ports:
        - "6680:6680"
        - "6600:6600"
    environment:
        - PIP_PACKAGES=Mopidy-dLeyna Mopidy-YouTube
       # - UPDATE=1
    volumes:
        - fifo:/tmp/snapcast/
        - ./music:/media/music
        - ./mopidydata:/mopidy
```
Best option is to rebuild the docker image local on your PC and use that image
```
git clone https://github.com/IVData/dockerfiles.git
cd dockerfiles/mopidy
nano Dockerfile
```
in Dockerfile after line 35 add 
```
    libdbus-glib-1-dev \
    dleyna-server \

``` 
and after line 46 add

```
    Mopidy-dLeyna \
    dbus-python \

```
save the Dockerfile and build your image make sure u copy the last dot on the build command 

```
 docker build --no-cache -t yourimage/mopidy .
```
than in your docker-compose.yml

```
version: '3'

services:
  mopidy:
    image: yourimage/mopidy
    container_name: mopidy
    hostname: mopidy
    network_mode: host
#    environment:
#      - UPDATE=1
    ports:
      - 6680:6680
      - 6600:6600
    volumes:
      - ./fifo:/tmp/snapcast/
      - ./music:/media/music
      - ./mopidydata:/mopidy

```
