### ISSUE TITLE
[Info] (Server) onResync (MopidyPipe) Causes momentary loss of stream on all Clients

### ISSUE THREAD

**Issue by pcwii** [IVData/dockerfiles#32]
Thanks for this great repo. I have both Mopidy and Snapserver installed with docker via a portainer stack.
For the most part things are working as expected but intermittently (~15-20 minutes) my stream is dropped then re-established. It will only be lost for a second but is very noticeable. This dropped stream occurs on all clients so I am concluding that this is something to do with the server end of things. I notice every time this occurs there is a server log entry as follows...`[Info] (Server) onResync (MopidyPipe): xxx.yyy ms`
I have a few questions.
1. Is there a setting I can make to the server configuration to limit or eliminate these drops?
2. Is it possible to use a tcp connection for the stream in docker (I currently use a snapfifo), would this be better?
3. I noticed the dockerhub link for Ivdata now links to this github, are you the new maintainer?
thanks!

**Comment by hamishfagg** [comment]
Hi,
I have seen this, I've just got covid atm and don't really have the brain power to explore it. Is that log message coming from Mopidy or Snapserver?

1. I don't know what's causing this off the top of my head, so I don't know yet.
2. Apparently you can use tcp as a source for snapcast, so that might be a better way to go, will have to test it.
3. I've just changed my github username is all, so I'm the original maintainer ;)

If you're up for it, there is a section here on configuring snapserver to use tcp, and it even has an example of how to configure mopidy to use tcp too: https://github.com/badaix/snapcast/blob/master/doc/configuration.md#tcp-server

**Comment by pcwii** [comment]
Thanks for the reply. The log file is coming from the Server container. I have had the tcp server working previously between two computers but was unable to get it working between containers, It may very well be the container network configuration. Unfortunately I know only enough about container deployment to be dangerous. I will have a look at the link you provided and see if I can get tcp working, and will provide feedback on my success or failure. Thanks for some great software and I hope you are feeling better soon!

**Comment by pcwii** [comment]
For reference I managed to get TCP working with the following settings.
1. Added `source = tcp://10.5.0.5:4953?name=MopidyTCP&mode=server` to my snapserver.conf file
2. Added `output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! tcpclientsink host=10.5.0.5 port=4953` to my mopidy.conf file
3. Ran the following compose file (portainer stack) to get the ports and networks for the container(s)
```

# Working with TCP Server 2022-08-21
version: '3.3'
services:
    # Snapcast Server 
    snapserver:
        restart: always
        container_name: snapserver
        environment:
            - TZ=america/toronto
        volumes:
            - /home/pcwii/docker/snapfifo:/tmp/snapcast                         #Shared Fifo Volume **Not used for TCP***
            - /home/pcwii/docker/snapcast/snapserver.conf:/etc/snapserver.conf  #Snapcast Configuration
        ports:
            - 1704:1704
            - 1705:1705
            - 1780:1780
            - 4953:4953                                                         # Required for TCP Server Connection
        networks:
          vpcbr:
            ipv4_address: 10.5.0.5                                              # Create Predictable IP Address for TCP Connection
        image: ivdata/snapserver:latest
    # Mopidy Server
    mopidy:
        container_name: mopidy
        environment:
            - TZ=america/toronto
        volumes:
            - /home/pcwii/docker/snapfifo:/tmp/snapcast/                        #Shared Fifo Volume
            - /mnt/storage/Media/Music:/media:ro                                #Music Library
            - /home/pcwii/docker/mopidy/data:/var/lib/mopidy
            - /home/pcwii/docker/mopidy/:/home/mopidy/.config/mopidy            #Mopidy Configuration
        ports:
            - 6600:6600
            - 6680:6680
            - 6681:6681
        networks:
          vpcbr:
            ipv4_address: 10.5.0.6                                              # Create Predictable IP Address for TCP Connection
        image: ivdata/mopidy:latest

# Network Configuration is required so the Mopidy and SnapServer can be on the same lan for TCP connection
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
```
I will continue to monitor to see if this changes corrects my stream drop outs.
Once confirmed I will close this Issue.
