### ISSUE TITLE
Trying your multiroom compose file, problems connecting to snapserver

### ISSUE THREAD

**Issue by ovizii** [IVData/dockerfiles#36]
I put both containers into the same network and defined their hostnames via:

```
    mopidy:                                                                                                                                          
        image: "ivdata/mopidy"                                                                                                                       
        container_name: mopidy                                                                                                                       
        hostname: mopidy                                                                                                                             
        networks:                                                                                                                                    
          - audio-streaming
```

and
```
    snapserver:                                                                                                                                      
        image: "ivdata/snapserver"                                                                                                                   
        container_name: snapserver                                                                                                                   
        hostname: snapserver                                                                                                                         
        networks:                                                                                                                                    
          - audio-streaming                                                                                                                          
        ports:                                                                                                                                       
            - "1704:1704"                                                                                                                            
            - "1705:1705"                                                                                                                            
            - "1780:1780"
```

Inside iris this does not work:
![image](https://user-images.githubusercontent.com/837902/225075656-70f51cd8-f1ad-4c62-ba3a-9f245b5ff0af.png)

If I access snapserver via the IP of the docker host it works:

![image](https://user-images.githubusercontent.com/837902/225075836-1a3d4e4c-bdb1-4c1a-8e7d-f20eef9e0b55.png)

Any ideas?
